### ISSUE TITLE
How about adding other type like srt and more?

### ISSUE THREAD

**Issue by Htet04** [Spikatrix/LRC-Editor#33]
I am just starting learning programing language. First Sketchware, AIDE I just know a very few java code , a very very few xml ,etc.. And I have try to made an app like your.But it is not OK with Me.
An I want to learn more too. BTW I just have an Android phone 8.1.0 android version. Aaaaaa..... More thing to say but I'll end here. 🎉

**Comment by Spikatrix** [comment]
SRT is a different format used primarily for video subtitles and I think It'll make more sense to create it as a separate new app rather than integrate it into LRC Editor because as the name of the app suggests, LRC Editor should be for editing lrc files.

By the way, I'd recommend running Android Studio on a PC if you want to learn more about Android Development.
